name: Staging Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    # uses GitHub environment
    environment:
      name: Staging
      url: "https://uat.sel.saishiko.com"

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to staging
      uses: appleboy/ssh-action@master
      env:
        SSH_BUILD_DIRECTORY: ${{ secrets.SSH_BUILD_DIRECTORY }}
        SSH_POST_BUILD_SCRIPT: post_build_script.sh
      with:
        host: 'uat.sel.saishiko.com'
        username: 'ubuntu'
        port: '22'
        key: |
              ---Enter Private Key--
        envs: SSH_BUILD_DIRECTORY,SSH_POST_BUILD_SCRIPT
        script: |
          cd /var/www/html/moodle/local/moodle-survey

          echo "Pulling latest code"
          sudo git pull

          echo "Purging caches"
          cd ..
          cd ..
          php admin/cli/purge_caches.php
